<p style="text-align:center;background:#ccc;color:#000;"> <strong> FINANCIAL PERFORMANCE </strong><strong>(30 scores)</strong></p>
<p>This Indicator will measure compliance with financial Regulations, Circulars, Standards, and Best Practices. It measures how an entity ensures profitability, control costs, generates a return to shareholders while serving its core service delivery, attracts future investments and customers, and manages financial risks (incl. controlling debt levels).</p>
<p><strong>FINANCIAL SUSTAINABILITY (20%)</strong></p>
<table style="width:100% !important;" border="1">
<tbody>
<tr style="background:#ccc;color:#000;">
<td rowspan="2" width="150">
<p><strong>Objectives/Strategies</strong></p>
</td>
<td rowspan="2" width="180">
<p><strong>Annual Target 2021/2022</strong></p>
</td>
<td rowspan="2" width="144">
<p><strong>Key Performance Indicators</strong></p>
</td>
<td rowspan="2" width="66">
<p><strong>Weight (%)</strong></p>
</td>
<td colspan="2" width="162">
<p><strong>Baseline/ Benchmark</strong></p>
</td>
<td width="102">
<p><strong>Indicator Target Value</strong></p>
</td>
<td width="108">
<p><strong>Actual Performance </strong></p>
</td>
</tr>
<tr style="background:#ccc;color:#000;">
<td width="84">
<p><strong>2019/20</strong></p>
</td>
<td width="78">
<p><strong>2020/21</strong></p>
</td>
<td width="102">
<p><strong>2021/22</strong></p>
</td>
<td width="108">
<p><strong>2021/22</strong></p>
</td>
</tr>
<tr>
<td rowspan="5" width="150">
<p>Targeted Marketing, Business growth and profitability improved.</p>
</td>
<td width="180">
<p>Annual gross profit worth Tzs. <strong>3,029,269,206</strong> generated by June 2022.</p>
</td>
<td width="144">
<p>Percentage of profit generated</p>
</td>
<td width="66">
<p>5</p>
</td>
<td width="84">
<p>27%</p>
</td>
<td width="78">
<p>85%</p>
</td>
<td width="102">
<p>100%</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Dividend worth Tzs.. <strong>100,000,000</strong> generated by June 2020</p>
</td>
<td width="144">
<p>Percentage of dividend generated</p>
</td>
<td width="66">
<p>1</p>
</td>
<td width="84">
<p>-</p>
</td>
<td width="78">
<p>-</p>
</td>
<td width="102">
<p>100%</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Debts amounting Tzs <strong>24,216,297,192 </strong>collected by June 2022</p>
</td>
<td width="144">
<p>Percentage of Debts Collected</p>
</td>
<td width="66">
<p>3</p>
</td>
<td width="84">
<p>100%</p>
</td>
<td width="78">
<p>45%</p>
</td>
<td width="102">
<p>99%</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Revenue of Tzs  <strong>3,377,393,600</strong> from Real Estate business generated by June 2022</p>
</td>
<td width="144">
<p>Percentage of Revenue generated from Real Estate Business</p>
</td>
<td width="66">
<p>2</p>
</td>
<td width="84">
<p>64%</p>
</td>
<td width="78">
<p>65%</p>
</td>
<td width="102">
<p>95%</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Cost Accounting Model Developed and Implemented by June 2022</p>
</td>
<td width="144">
<p>Costing Accounting model in place</p>
</td>
<td width="66">
<p>2</p>
</td>
<td width="84">
<p>0</p>
</td>
<td width="78">
<p>0</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td rowspan="3" width="150">
<p>Institutional Management and Capacity to deliver Quality Services improved</p>
</td>
<td rowspan="2" width="180">
<p>Annual Corporate plans and Budget for FY 2022/2023 prepared and approved by June 2022</p>
</td>
<td width="144">
<p>Approved Annual corporate plan in place</p>
</td>
<td width="66">
<p>3</p>
</td>
<td width="84">
<p>1</p>
</td>
<td width="78">
<p>1</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="144">
<p>Approved annual budget in place</p>
</td>
<td width="66">
<p>2.5</p>
</td>
<td width="84">
<p>1</p>
</td>
<td width="78">
<p>1</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Timely preparation and submission of Quarterly and Annual performance reports to relevant authorities by June 2022.</p>
</td>
<td width="144">
<p>Number of statutory reports prepared and submitted</p>
</td>
<td width="66">
<p>2</p>
</td>
<td width="84">
<p>5</p>
</td>
<td width="78">
<p>5</p>
</td>
<td width="102">
<p>5</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td rowspan="3" width="150">
<p>Mobilization of financial Resource for Investment in Postal enhanced.</p>
</td>
<td width="180">
<p>Loans, financial resources and other support from Development Partners secured by June 2022</p>
</td>
<td width="144">
<p>Number  of projects secured from development partners</p>
</td>
<td width="66">
<p>3</p>
</td>
<td width="84">
<p>-</p>
</td>
<td width="78">
<p>2</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Development of four (4) project proposals for acquisition of funds from government, investors and partners to support Postal services by June 2021.</p>
</td>
<td width="144">
<p>Number of project proposals</p>
</td>
<td width="66">
<p>3</p>
</td>
<td width="84">
<p>-</p>
</td>
<td width="78">
<p>7</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td width="180">
<p>Ensure effective implementation and supervision of 3 development projects and programmes by June 2022</p>
</td>
<td width="144">
<p>Number of projects implemented and monitored</p>
</td>
<td width="66">
<p>3.5</p>
</td>
<td width="84">
<p>-</p>
</td>
<td width="78">
<p>7</p>
</td>
<td width="102">
<p>3</p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
<tr>
<td colspan="2" width="330">
<p><strong>TOTAL</strong></p>
</td>
<td width="144">
<p><strong> </strong></p>
</td>
<td width="66">
<p><strong>30</strong></p>
</td>
<td width="84">
<p>-</p>
</td>
<td width="78">
<p> </p>
</td>
<td width="102">
<p> </p>
</td>
<td width="108">
<p> </p>
</td>
</tr>
</tbody>
</table>