<p style="color:#1976d2;"> <strong>SECTION A: INTRODUCTION</strong></p>
<p>This instrument provides an objective basis for performance evaluation of Tanzania Posts Corporation (TPC) in relation to achievements made and to set goals for the coming fiscal year. The instrument is to be used by the Postmaster General (PMG) in consultation with the General Manager Corporate Resources Management (GM/CRM) to make a self-evaluation of the Corporate Resources Management  Division and for the PMG to gauge the achievements of GM/CRMand agree with the PMG on commitments for the following fiscal year.</p>
<p>The evaluation employs both numerical and qualitative assessment. The numerical assessment uses a rating system to compare performance results against yearly targets drawn from the institutions strategic and annual work plans. The instrument consists of the following sections:</p>
<ul>
<li><strong>Section A: Introduction</strong>. This section presents the key matters contained in the instrument and elaborates on how it is to be filled by the concerned parties;</li>

<li><strong>Section B: Targets for Subsequent Evaluation</strong>. This section contains the GM/CRM commitment for the current year, enumerating the targets that will form basis for assessment at the end of the fiscal year. At that time these targets will form part of section B of the instrument (section described above). As mentioned earlier, these targets are drawn from the institution’s strategic and annual work plans. The GM/CRM and PMG’s input in this section will mainly consist of remarks on the targets. The remarks made will be taken on board during the rating exercise at the end of the year.</li>

<li><strong>Section C: Evaluation</strong>. This section contains the achievements of GM/CRM and TPC during the past year. The achievements are presented against the performance targets for the year and contain subsections (columns on the matrix) for GM/CRM self-assessment and comments explaining the basis of assessment and sub-section for the PMG’s rating and comments followed by a section presenting the agreed final rating. The meanings of the ratings are presented in Annex A. Note: since this exercise is starting this year, this section is presented in the instrument for demonstration and will not be filled.</li>

<li><strong>Section D: Commitment</strong>. This will be the place where the GM/CRMand PMG sign the document to underpin the commitments done</li>
</ul>
