<p style="color:#1976d2;"> SECTION C: EVALUATION</p>
<p><strong>2. ACHIEVEMENTS OF TARGETS</strong></p>
<p style="text-align:center;background:#ccc;color:#000;">  <strong>TABLE 6: EVALUATION MATRIX*</strong></p>
<table style="width:100% !important;" border="1">
<tbody>
<tr style="background:#ccc;color:#000;">
<td rowspan="2" width="38">
<p><strong> </strong></p>
<p><strong> </strong></p>
<p><strong>No.</strong></p>
</td>
<td rowspan="2" width="292">
<p><strong>Performance Goal</strong></p>
</td>
<td rowspan="2" width="102">
<p><strong> </strong></p>
<p><strong>Performance Weight</strong></p>
<p><strong> </strong></p>
</td>
<td colspan="2" width="198">
<p><strong>Board’s Self-Assessment</strong></p>
</td>
<td colspan="2" width="228">
<p><strong>TR’s Assessment</strong></p>
</td>
<td rowspan="2" width="76">
<p><strong> </strong></p>
<p><strong>Agreed Rating</strong></p>
</td>
</tr>
<tr style="background:#ccc;color:#000;">
<td width="96">
<p><strong>Board’s Self Rating</strong></p>
</td>
<td width="102">
<p><strong>Board’s Comments / Explanation</strong></p>
</td>
<td width="78">
<p><strong>TR’s</strong></p>
<p><strong>Rating</strong></p>
</td>
<td width="150">
<p><strong>TR’s Comments and Explanation Regarding Strengths and Weaknesses</strong></p>
</td>
</tr>
<tr>
<td width="38">
<p> </p>
<p>1.</p>
</td>
<td width="292">
<p>Annual gross profit worth Tzs. <strong>3,029,269,206</strong> generated by June 2022.</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>2.</p>
</td>
<td width="292">
<p>Revenue worth Tzs<strong>40,761,234,400</strong> generated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>3.</p>
</td>
<td width="292">
<p>Debts amounting Tzs<strong>24,216,297,192 </strong>collected by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>4.</p>
</td>
<td width="292">
<p>Revenue of <strong>Tzs. 13,216,017,000</strong> from Mails Business generated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>5.</p>
</td>
<td width="292">
<p>Revenue of Tzs<strong>21,711,126,800 </strong>from EMS Business generated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>6.</p>
</td>
<td width="292">
<p>Revenue amounting Tzs<strong>1,072,667,000</strong>   from Financial and Agency Business (FAS) generated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>7.</p>
</td>
<td width="292">
<p>Revenue amounting Tzs<strong>310,161,000</strong> from E-Business generated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>8.</p>
</td>
<td width="292">
<p>Revenue amounting Tzs<strong>913,941,000</strong> from Bureau De Change business by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>9.</p>
</td>
<td width="292">
<p>Revenue of Tzs<strong>1,976,205,010</strong> from Post Cargo Truck generated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>10.</p>
</td>
<td width="292">
<p>Timely preparation and submission of Quarterly and Annual performance reports to relevant authorities by June 2022.</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>16</p>
</td>
<td width="292">
<p>Ten (10) Huduma Pamoja centers (One stop Center)established and cordinated by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>17</p>
</td>
<td width="292">
<p>Ensure postal services are available in the PMIS system (Postal Management Information System) and enhance Postal Kiganjani System by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>18</p>
</td>
<td width="292">
<p>Postal Digital Map developed and operarationalized to enhance transportation delivery of letters, parcels and small packets and strengthern laboratory sample transportation  project by June 2022</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>19</p>
</td>
<td width="292">
<p>ISO 9001:2015 Quality management certificate attained by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>20</p>
</td>
<td width="292">
<p>UPU quality management Certificate obtained by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>21</p>
</td>
<td width="292">
<p>EMS Pay for performance targets set by EMS Cooperative achieved by June 2022</p>
</td>
<td width="102">
<p>8</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>22</p>
</td>
<td width="292">
<p>Parcel performance  targets set by UPU achieved by June 2022</p>
</td>
<td width="102">
<p>16</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>23</p>
</td>
<td width="292">
<p>Registered and insured items target set are achieved by 2022</p>
</td>
<td width="102">
<p>6</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>24</p>
</td>
<td width="292">
<p>Number of complaints reduced by 10% by June 2022</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>25</p>
</td>
<td width="292">
<p>New corporate(Major)  customers solicited and customer relationship enhanced by June 2022</p>
</td>
<td width="102">
<p>10</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>25</p>
</td>
<td width="292">
<p>TPC market share increased by  10% and corporate Brand awareness improved by June 2022</p>
</td>
<td width="102">
<p>5</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>26</p>
</td>
<td width="292">
<p>Volume of Mails Business increased by 10% by June 2022</p>
</td>
<td width="102">
<p>3</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>27</p>
</td>
<td width="292">
<p>Volume of EMS Business increased by 15% by June 2022</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>28</p>
</td>
<td width="292">
<p>Postal Digital platform through ECOM and Digital Tanzania initiatives developed and operationalized by June 2022</p>
</td>
<td width="102">
<p>1.5</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>29</p>
</td>
<td width="292">
<p>Automation of TPC operations (VAT, HR, counter automation, car packing, dispatch system and billing system) enhanced by June 2022.</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>30</p>
</td>
<td width="292">
<p>Level of ICT usage strengthened and improved by June 2024</p>
</td>
<td width="102">
<p>2.5</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>31</p>
</td>
<td width="292">
<p>Working tools, equipment and facilities procured, installed and maintained by June 2022</p>
</td>
<td width="102">
<p>4</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>32</p>
</td>
<td width="292">
<p>Bureau de Change branches expanded from 26 to 31 in all prioritized strategic areas by June 2022</p>
</td>
<td width="102">
<p>2</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>32</p>
</td>
<td width="292">
<p>Ten (10)  consultant mission for UPU Member countries in Africa region, English speaking and Mozambique coordinated by June 2022</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>33</p>
</td>
<td width="292">
<p>15 ICT Systems (IPS, IFS, CDS, SMARTPOSTA systems) maintained by June, 2022</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>34</p>
</td>
<td width="292">
<p>Ensure statutory deductions, staff benefits and welfare timely provided by June, 2022.</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>35</p>
</td>
<td width="292">
<p>Automation of staff performance management system (KPIs) through Posta Management Information System (PMIS) by June 2022.</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>36</p>
</td>
<td width="292">
<p>Actions to Combat Corruption at workplace undertaken by June 2022.</p>
</td>
<td width="102">
<p>1.5</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>37</p>
</td>
<td width="292">
<p>Forty-eight (48) ordinary Division meetings conducted by June 2022</p>
</td>
<td width="102">
<p>1</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p>38</p>
</td>
<td width="292">
<p>ERM Framework and register (risk log) reviewed, monitored and evaluated  by 2022</p>
</td>
<td width="102">
<p>2.5</p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
<tr>
<td width="38">
<p> </p>
</td>
<td width="292">
<p><strong>TOTAL</strong></p>
</td>
<td width="102">
<p><strong>100</strong></p>
</td>
<td width="96">
<p><strong> </strong></p>
</td>
<td width="102">
<p><strong> </strong></p>
</td>
<td width="78">
<p><strong> </strong></p>
</td>
<td width="150">
<p><strong> </strong></p>
</td>
<td width="76">
<p><strong> </strong></p>
</td>
</tr>
</tbody>
</table>
<p><strong> </strong></p>
<p><strong> </strong></p>
<p><strong><br /> </strong></p>
<p><strong> </strong></p>